export const footerLinks = [
  [
    {
      id: 1,
      content: {
        English: "Udemy Business",
        Bngl: "উডেমি ব্যবসা",
        Chin: "优达学城",
      },
      url: "/",
    },
    {
      id: 2,
      content: {
        English: "Teach on Udemy",
        Bangla: "উডেমিতে পড়ান",
        China: "在优达学城教学",
      },
      url: "/",
    },
    {
      id: 3,
      content: {
        English: "Get the app",
        Bangla: "অ্যাপটি ডাউনলোড করুন",
        China: "下载应用程序",
      },
      url: "/",
    },
    {
      id: 4,
      content: {
        English: "About us",
        Bangla: "আমাদের সম্পর্কে",
        China: "关于我们",
      },
      url: "/",
    },
    {
      id: 5,
      content: {
        English: "Contact us",
        Bangla: "যোগাযোগ করুন",
        China: "联系我们",
      },
      url: "/",
    },
  ],
  [
    {
      id: 1,
      content: { English: "Careers", Bangla: "ক্যারিয়ার", China: "职业" },
      url: "/",
    },
    {
      id: 2,
      content: { English: "Blog", Bangla: "ব্লগ", China: "博客" },
      url: "/",
    },
    {
      id: 3,
      content: {
        English: "Help and Support",
        Bangla: "সাহায্য এবং সহায়তা",
        China: "帮助与支持",
      },
      url: "/",
    },
    {
      id: 4,
      content: {
        English: "Affiliate",
        Bangla: "অ্যাফিলিয়েট",
        China: "联盟计划",
      },
      url: "/",
    },
    {
      id: 5,
      content: {
        English: "Investors",
        Bangla: "বিনিয়োগকারীরা",
        China: "投资者",
      },
      url: "/",
    },
  ],
  [
    {
      id: 1,
      content: { English: "Terms", Bangla: "শর্তাবলী", China: "条款" },
      url: "/",
    },
    {
      id: 2,
      content: {
        English: "Privacy policy",
        Bangla: "গোপনীয়তা নীতি",
        China: "隐私政策",
      },
      url: "/",
    },
    {
      id: 3,
      content: {
        English: "Cookie settings",
        Bangla: "কুকি সেটিংস",
        China: "Cookie设置",
      },
      url: "/",
    },
    {
      id: 4,
      content: { English: "Sitemap", Bangla: "সাইটম্যাপ", China: "网站地图" },
      url: "/",
    },
    {
      id: 5,
      content: {
        English: "Accessibility statement",
        Bangla: "অ্যাক্সেসযোগ্যতার বিবৃতি",
        China: "可及性声明",
      },
      url: "/",
    },
  ],
];

export const skillsList = [
  {
    id: 1,
    title: "Web Development",
    items: [
      { id: 1, text: "Web Development", user: "13.3M+Learners" },
      { id: 2, text: "", user: "13.3M+Learners" },
      { id: 3, text: "", user: "13.3M+Learners" },
      { id: 4, text: "", user: "" },
      { id: 5, text: "", user: "" },
      { id: 6, text: "", user: "" },
      { id: 7, text: "", user: "" },
      { id: 8, text: "", user: "" },
    ],
    cardItems: [
      {
        id: 1,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 1,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 1,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 1,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 1,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
    ],
  },

  {
    id: 2,
    title: "IT Certifications",
    items: [
      { id: 1, text: "" },
      { id: 2, text: "" },
      { id: 3, text: "" },
      { id: 4, text: "" },
      { id: 5, text: "" },
      { id: 6, text: "" },
      { id: 7, text: "" },
      { id: 8, text: "" },
    ],
    cardItems: [
      {
        id: 1,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 2,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 3,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 4,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 5,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
    ],
  },

  {
    id: 3,
    title: "Leadership",
    items: [
      { id: 1, text: "" },
      { id: 2, text: "" },
      { id: 3, text: "" },
      { id: 4, text: "" },
      { id: 5, text: "" },
      { id: 6, text: "" },
      { id: 7, text: "" },
      { id: 8, text: "" },
    ],
    cardItems: [
      {
        id: 1,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 2,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 3,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 4,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 5,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
    ],
  },

  {
    id: 4,
    title: "Data Science",
    items: [
      { id: 1, text: "" },
      { id: 2, text: "" },
      { id: 3, text: "" },
      { id: 4, text: "" },
      { id: 5, text: "" },
      { id: 6, text: "" },
      { id: 7, text: "" },
      { id: 8, text: "" },
    ],
    cardItems: [
      {
        id: 1,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 2,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 3,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 4,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 5,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
    ],
  },

  {
    id: 5,
    title: "Communication",
    items: [
      { id: 1, text: "" },
      { id: 2, text: "" },
      { id: 3, text: "" },
      { id: 4, text: "" },
      { id: 5, text: "" },
      { id: 6, text: "" },
      { id: 7, text: "" },
      { id: 8, text: "" },
    ],
    cardItems: [
      {
        id: 1,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 2,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 3,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 4,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 5,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
    ],
  },

  {
    id: 6,
    title: "Business Analytics & Intelligence",
    items: [
      { id: 1, text: "" },
      { id: 2, text: "" },
      { id: 3, text: "" },
      { id: 4, text: "" },
      { id: 5, text: "" },
      { id: 6, text: "" },
      { id: 7, text: "" },
      { id: 8, text: "" },
    ],
    cardItems: [
      {
        id: 1,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 2,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 3,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 4,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 5,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
    ],
  },
];
