import { IoIosStarOutline } from "react-icons/io";

export const footerLinks = [
  [
    {
      id: 1,
      content: {
        English: "Udemy Business",
        Bngl: "উডেমি ব্যবসা",
        Chin: "优达学城",
      },
      url: "/",
    },
    {
      id: 2,
      content: {
        English: "Teach on Udemy",
        Bangla: "উডেমিতে পড়ান",
        China: "在优达学城教学",
      },
      url: "/",
    },
    {
      id: 3,
      content: {
        English: "Get the app",
        Bangla: "অ্যাপটি ডাউনলোড করুন",
        China: "下载应用程序",
      },
      url: "/",
    },
    {
      id: 4,
      content: {
        English: "About us",
        Bangla: "আমাদের সম্পর্কে",
        China: "关于我们",
      },
      url: "/",
    },
    {
      id: 5,
      content: {
        English: "Contact us",
        Bangla: "যোগাযোগ করুন",
        China: "联系我们",
      },
      url: "/",
    },
  ],
  [
    {
      id: 1,
      content: { English: "Careers", Bangla: "ক্যারিয়ার", China: "职业" },
      url: "/",
    },
    {
      id: 2,
      content: { English: "Blog", Bangla: "ব্লগ", China: "博客" },
      url: "/",
    },
    {
      id: 3,
      content: {
        English: "Help and Support",
        Bangla: "সাহায্য এবং সহায়তা",
        China: "帮助与支持",
      },
      url: "/",
    },
    {
      id: 4,
      content: {
        English: "Affiliate",
        Bangla: "অ্যাফিলিয়েট",
        China: "联盟计划",
      },
      url: "/",
    },
    {
      id: 5,
      content: {
        English: "Investors",
        Bangla: "বিনিয়োগকারীরা",
        China: "投资者",
      },
      url: "/",
    },
  ],
  [
    {
      id: 1,
      content: { English: "Terms", Bangla: "শর্তাবলী", China: "条款" },
      url: "/",
    },
    {
      id: 2,
      content: {
        English: "Privacy policy",
        Bangla: "গোপনীয়তা নীতি",
        China: "隐私政策",
      },
      url: "/",
    },
    {
      id: 3,
      content: {
        English: "Cookie settings",
        Bangla: "কুকি সেটিংস",
        China: "Cookie设置",
      },
      url: "/",
    },
    {
      id: 4,
      content: { English: "Sitemap", Bangla: "সাইটম্যাপ", China: "网站地图" },
      url: "/",
    },
    {
      id: 5,
      content: {
        English: "Accessibility statement",
        Bangla: "অ্যাক্সেসযোগ্যতার বিবৃতি",
        China: "可及性声明",
      },
      url: "/",
    },
  ],
];

export const skillsList = [
  {
    id: 1,
    title: "Web Development",
    items: [
      { id: 1, text: "Web Development", user: "13.3M+Learners" },
      { id: 2, text: "JavaScript", user: "17.7  M+Learners" },
      { id: 3, text: "React JS", user: "7M+Learners" },
      { id: 4, text: "Angular", user: "4M+Learners" },
      { id: 5, text: "Java", user: "15.5M+Learners" },
      { id: 6, text: "Android Development", user: "8M+Learners" },
      { id: 7, text: "IOS Development", user: "4M+Learners" },
      { id: 8, text: "CSS", user: "9M+Learners" },
    ],
    cardItems: [
      {
        id: 1,
        imgSrc:
          "https://media.istockphoto.com/id/1290492381/photo/3d-code-programming-for-website-editors-view.jpg?s=1024x1024&w=is&k=20&c=9M-O33J-9jLuAVd096VRd5So8YGYvj6iJH_cLjjmlhk=",
        title: "The Complete 2024 Web",
        subTitle: " Devlopment Bootcamp",
        author: " Dr.Angela Yu Developer and lead...",
        rating: "4.7",
        ratingIcons: [
          { id: 1, icon: IoIosStarOutline },
          { id: 2, icon: IoIosStarOutline },
          { id: 3, icon: IoIosStarOutline },
          { id: 4, icon: IoIosStarOutline },
          { id: 5, icon: IoIosStarOutline },
        ],
        ratingCounter: "(410,318)",
        currentPrice: "$12.99",
        beforePrice: "$69.99",
        mostSell: "Bestseller",
      },
      {
        id: 2,
        imgSrc:
          "https://plus.unsplash.com/premium_photo-1678565202049-9e37b2da8060?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fHdlYiUyMGRldmVsb3BtZW50fGVufDB8fDB8fHww",
        title: "The Web Developer Bootcamp",
        subTitle: " Devlopment Bootcamp",
        author: "Colt Steel",
        rating: "4.7",
        ratingIcons: [
          { id: 1, icon: IoIosStarOutline },
          { id: 2, icon: IoIosStarOutline },
          { id: 3, icon: IoIosStarOutline },
          { id: 4, icon: IoIosStarOutline },
          { id: 5, icon: IoIosStarOutline },
        ],
        ratingCounter: "(276,801)",
        currentPrice: "$19.99",
        beforePrice: "$84.99",
      },
      {
        id: 3,
        imgSrc:
          "https://images.unsplash.com/photo-1585384107568-5bc588c7eefd?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fHdlYiUyMGRldmVsb3BtZW50fGVufDB8fDB8fHww",
        title: "Web Development Masterclass-",
        subTitle: " Online certification Course",
        author: "YouAccel Training",
        rating: "4.3",
        ratingIcons: [
          { id: 1, icon: IoIosStarOutline },
          { id: 2, icon: IoIosStarOutline },
          { id: 3, icon: IoIosStarOutline },
          { id: 4, icon: IoIosStarOutline },
          { id: 5, icon: IoIosStarOutline },
        ],
        ratingCounter: "(10,005)",
        currentPrice: "$12.99",
        beforePrice: "$69.99",
      },
      {
        id: 4,
        imgSrc:
          "https://media.istockphoto.com/id/1456339578/photo/developing-programming-and-coding-technologies-professional-developer-programmer-cooperation.webp?a=1&b=1&s=612x612&w=0&k=20&c=d-61mo1-S520J8dT80uAYu__Wnoz0n1f8VhLF76VxW0=",
        title: "The Complete Web Developer",
        subTitle: "Course 3.0 ",
        author: "Percival,Codestars .over 2 million...",
        rating: "4.4",
        ratingIcons: [
          { id: 1, icon: IoIosStarOutline },
          { id: 2, icon: IoIosStarOutline },
          { id: 3, icon: IoIosStarOutline },
          { id: 4, icon: IoIosStarOutline },
          { id: 5, icon: IoIosStarOutline },
        ],
        ratingCounter: "72,294",
        currentPrice: "$19.99",
        beforePrice: "$84.99",
      },
    ],
  },

  {
    id: 2,
    title: "IT Certifications",
    items: [
      { id: 1, text: "" },
      { id: 2, text: "" },
      { id: 3, text: "" },
      { id: 4, text: "" },
      { id: 5, text: "" },
      { id: 6, text: "" },
      { id: 7, text: "" },
      { id: 8, text: "" },
    ],
    cardItems: [
      {
        id: 1,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 2,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 3,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 4,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 5,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
    ],
  },

  {
    id: 3,
    title: "Leadership",
    items: [
      { id: 1, text: "" },
      { id: 2, text: "" },
      { id: 3, text: "" },
      { id: 4, text: "" },
      { id: 5, text: "" },
      { id: 6, text: "" },
      { id: 7, text: "" },
      { id: 8, text: "" },
    ],
    cardItems: [
      {
        id: 1,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 2,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 3,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 4,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 5,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
    ],
  },

  {
    id: 4,
    title: "Data Science",
    items: [
      { id: 1, text: "" },
      { id: 2, text: "" },
      { id: 3, text: "" },
      { id: 4, text: "" },
      { id: 5, text: "" },
      { id: 6, text: "" },
      { id: 7, text: "" },
      { id: 8, text: "" },
    ],
    cardItems: [
      {
        id: 1,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 2,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 3,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 4,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 5,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
    ],
  },

  {
    id: 5,
    title: "Communication",
    items: [
      { id: 1, text: "" },
      { id: 2, text: "" },
      { id: 3, text: "" },
      { id: 4, text: "" },
      { id: 5, text: "" },
      { id: 6, text: "" },
      { id: 7, text: "" },
      { id: 8, text: "" },
    ],
    cardItems: [
      {
        id: 1,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 2,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 3,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 4,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 5,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
    ],
  },

  {
    id: 6,
    title: "Business Analytics & Intelligence",
    items: [
      { id: 1, text: "" },
      { id: 2, text: "" },
      { id: 3, text: "" },
      { id: 4, text: "" },
      { id: 5, text: "" },
      { id: 6, text: "" },
      { id: 7, text: "" },
      { id: 8, text: "" },
    ],
    cardItems: [
      {
        id: 1,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 2,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 3,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 4,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
      {
        id: 5,
        imgSrc: "",
        title: "",
        subTitle: "",
        rating: "4",
        totalRating: "3453",
        currentPrice: "43",
        beforePrice: "34",
        mostSell: "Bestseller",
      },
    ],
  },
];
